# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
        update-type: "all"
    ignore:
      - dependency-name: "package-to-ignore"
    reject:
      - dependency-name: "package-to-reject"
        reason: "This package has a known security vulnerability."
    automerge:
      - dependency-name: "package-to-automerge"
        schedule:
          interval: "hourly"
        labels:
          - "automerge"
    reviewers:
      - type: "team"
        reviewers:
          - "team-name"
    # Grant triage access to GitHub AI
    collaborators:
      github-ai[bot]:
        permission: admin
    # Grant triage access to Dependabot
    collaborators:
      dependabot[bot]:
        permission: admin
